---
title: "Data Wrangling"
output: html_document
---

```{r}
library(tidyverse)
```

Import FAS csv files

*Importing FAS litters file
```{r}
#do not use read.csv
#use the relative directory - file within the working directory

litters_data = read_csv(file="./data/data_import_examples/FAS_litters.csv")

#cleans up variable names - remove spaces
litters_data = janitor::clean_names(litters_data)
```

*Importing FAS pups file
```{r}
pups_data = read_csv(file="./data/data_import_examples/FAS_pups.csv")

#cleans up variable names - remove spaces
pups_data = janitor::clean_names(pups_data)
```

Initial look at the data
```{r}
#look at the first few rows
head(litters_data)

#look at the last few rows
tail(litters_data)

#quick summary statistics of your variables - missing values, mean, sd, histogram, etc. 
skimr::skim(litters_data)

```


Skipping rows; omitting variable names
```{r}
litters_data = read_csv(file = "./data/data_import_examples/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

Parsing columns - can give explicit column specifications
```{r}
litters_data = read_csv(file = "./data/data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)

#can also use the shorthand
litters_data = read_csv(file = "./data/data_import_examples/FAS_litters.csv",
  col_types = "ccddiiii"
)

pups_data = read_csv("./data/data_import_examples/FAS_pups.csv", col_types = "ciiiii")
skimr::skim(pups_data)
```

If the file is not a csv:
```{r}
library(readxl)
mlb_data = read_excel("data/data_import_examples/mlb11.xlsx", n_max = 20)

mlb_subset = readxl::read_excel("data/data_import_examples/mlb11.xlsx", n_max = 20,
                                range = "A1:E17")
```

